### ISSUE TITLE
Create Schedule of activities till the end of the course

### ISSUE THREAD

**Issue by bobbyreed** [Sreejapodupuganti/ERP#4]
- Sprint 3 (10/1-10/3)
  - (activities go here)
  - (activities go here)
- Sprint 4 (10/3 - 10/8)
  - (activities go here)
  - (activities go here)

**Comment by Satyasubbu** [comment]
Sprint 3 (10/1-10/3)
(UML diagrams)
(Schedule of implementation) 
(Software documentation)

Sprint 4 (10/3 - 10/8)
(One developed and functional feature/service )
(software documentation continued )
(Requirements documents)

**Comment by bobbyreed** [comment]
Great! We will use this to check in on Thursdays.
